services:
  shiva_ratri:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: shiva_ratri
    ports:
      - "9393:9393"
    volumes:
      - ./api:/var/www/api
      - /var/www/api/vendor